### ISSUE TITLE
NewTab Adaptor doesn't really focus web page when a new tab is created.

### ISSUE THREAD

**Issue by crocket** [gdh1995/vimium-c-helpers#1]
Vimium C Setting

![2020-03-30_Mon_07:44:09](https://user-images.githubusercontent.com/748856/77887448-8c76fd00-72a5-11ea-98e7-00a54fd32a7e.png)

NewTab Adaptor Setting

![2020-03-30_Mon_07:43:52](https://user-images.githubusercontent.com/748856/77887453-8f71ed80-72a5-11ea-8944-14e3b0d08152.png)

What happens when a new tab is created by pressing `t` or `Ctrl+t`.

![2020-03-30_Mon_07:45:06](https://user-images.githubusercontent.com/748856/77887500-a9133500-72a5-11ea-812f-367549441880.png)

Reproducible on

* google chrome
* vivaldi
* brave

**Comment by gdh1995** [comment]
Um, confirmed. It's because currently the default `newtab.html` doesn't support "Focus web page when ...", and if you replace it with other URLs like `chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html` and save options, then it should work.

**Comment by crocket** [comment]
It was already set to chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/blank.html

**Comment by gdh1995** [comment]
Then does it focus web page content successfully?

**Comment by crocket** [comment]
If it is set to

```
chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/blank.html
```

it shifts the focus to the web page.
