### ISSUE TITLE
pdfjs: keeping URLs unchanged breaks position restore 

### ISSUE THREAD

**Issue by tinywrkb** [gdh1995/vimium-c-helpers#12]
Reporting here as bug reporting is disabled for the pdfjs repo.

Microsoft Edge Dev 92.0.902.9 (Linux), Vimium C 1.90.2, PDF Viewer for Vimium C 2.7.111.

Enabling `Prefer keeping URLs in the address bar unchanged` breaks position restore set with `View position on load: Show previous position`.  

Might be outside the scope of this extension, but I'm using [Undisposition](https://chrome.google.com/webstore/detail/undisposition-racle-fork/bbppejejjfancffmhncgkhjdaikdgagc) to directly open PDFs in the browser instead of downloading them.  
Another issue caused by enabling the `keeping URLs unchanged` setting is that PDFs that are handled by `Undisposition` being opened by the Edge's built-in PDF viewer.  
**edit:** The `Undisposition` extension will introduce some issues, like breaking Google Drive downloads, so better avoid it.

Disabling that setting fixes both issues.

I don't know if this can be fixed but it would be helpful to at least add a warning next to the setting that it might clash with other features or extensions.

**Comment by tinywrkb** [comment]
Thanks for replying and moving the issue to the right place, I forgot about this repo.  

IDK about disabling the setting but a warning is warranted to avoid users being surprised by issues instigated by having the setting enabled and then opening new bugs.

Please feel free to close this issue if you don't believe it can be fixed.  

Reasons for wanting this to be fixed:  
1. PDFs can be opened directly in the mobile version of the browser from the synced tabs/history. This is great when the user starts reading on the desktop and then wants to continue on mobile.
2. I use the [Tab Session Manager](https://github.com/sienori/Tab-Session-Manager) extension to backup, save, and sync browser sessions (the latter feature currently semi-broken due to Google login token issue).  
To avoid creating superfluous sessions entries, some URLs like `extensions://*, `chorme://*/, and `edge://*` are filtered-out (not the default, it's a user setting).  
This means that open PDFs tabs won't be included in the saved session if `keeping URLs unchanged` is disabled.

**Comment by gdh1995** [comment]
Thanks. I'll take a try to fix this when Vimium C gets "stable" for a while.

You may have noticed that this option doesn't exist in the official PDF Viewer extension - it's added by myself and only limited tests (mainly on local files and paper websites) have been run.

There's one known (big) problem which can not be fixed - this option uses `fetch` API to download file data, while some websites may refuse such a way, which will make it show an error like the snapshot in https://github.com/gdh1995/vimium-c-helpers/issues/10#issuecomment-827574552 . In fact, this extension should disable the option for a while and reload the tab, but I have no time to implement it.

On the contrary, it may be possible to fix the above issues.

**Comment by tinywrkb** [comment]
The `Content-Disposition` hack does more harm than good, namely it breaks Google Drive downloads, so I stopped using the Undisposition extension.  
I mainly needed it for [calibre-web](https://github.com/janeczku/calibre-web/), and it's easy to patch the server instead of relying on an extension, with the extra benefit of working with all clients.

Recently I've been depending more on [Raindrop](https://raindrop.io/) and [Edge's Collections](https://support.microsoft.com/en-us/microsoft-edge/organize-your-ideas-with-collections-in-microsoft-edge-60fd7bba-6cfd-00b9-3787-b197231b507e), both can't handle `edge://` URLs, so I need to toggle the unchanged URL feature in order to save the page.  
For PDFs that I need to keep position and save for later, I think I will just use a web app, e.g. [Kami](https://www.kamiapp.com/), with the extra benefit of syncing position across devices.

So while it would be nice to see this being resolved, don't feel obligated to put it high on the TODO list.

**Comment by gdh1995** [comment]
Oh I see. But sorry I haven't much time to maintain this. You may need to wait for 1~2 months.

**Comment by tinywrkb** [comment]
Nice! I can also confirm that it's working now correctly.
