### ISSUE TITLE
bindings not working

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c-helpers#13]
I had no success setting up a global shortcut with Shortcut forwarding tool.
I've set up Shift+Alt+h as "Custom Shortcut 1" and in vimium-c I added `shortcut userCustomized1 command="showHelp"` and also `clnalilglegcjmlgenoppklmfppddien` to allowed list of other extension IDs but when I type Shift+Alt+h the regular the firefox builin help menu is shown.
 
I've tried also Ctrl+Alt+w for the shortcut and another command too.

**Comment by gdh1995** [comment]
Will Alt+Shift+H work if you set it on Vimium C's `custom shortcut 1`, instead of the one of Shortcut forwarding tool?

**Comment by gdh1995** [comment]
Um, if you're using Firefox, then `cl...` is not the ID of `Shortcut forwarding tool`.

**Comment by elig0n** [comment]
> Will Alt+Shift+H work if you set it on Vimium C's `custom shortcut 1`, instead of the one of Shortcut forwarding tool?

Can you show how to do it ? I'm not sure I understand
 
> BTW, Firefox 90 (Win 10, x64) doesn't accept `Alt+Shift+H` as a global shortcut - it says the composed key is "invalid".

I'm using 89 and it's accepting alt Alt+Shift+* shortcuts but they do not seem to work

**Comment by elig0n** [comment]
> The version published on Firefox Add-ons is `shortcut-forwarding-tool@gdh1995.cn`, while `clnalilglegcjmlgenoppklmfppddien` means its Chrome version.
I also got `shortcut-forwarding-tool@gdh1995.cn` there

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/126250110-4a412f4d-b8d8-461f-8b09-8a7d671aa973.png)

When configured following this snapshot, `Ctrl+Alt+X` will open a new tab.

BTW, `Alt+Shift+H` on Firefox 89 + my Win 10 seems also "invalid". What's your system name?

**Comment by elig0n** [comment]
I can confirm that Ctrl+Alt+? shortcuts work after doing step 4.

This is firefox 89.0.1 on Linux
