### ISSUE TITLE
Open vomnibar automatically

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c-helpers#16]
Hi @gdh1995 , is it possible to add an option to open the vombinar automatically? :-)

**Comment by gdh1995** [comment]
As said in https://github.com/gdh1995/vimium-c-helpers/issues/7#issuecomment-868224962 , Vimium C v1.92 has supported this feature: `map t createTab $then="Vomnibar.activate"`.

`$then` can be ~~a mapped key sequence~~ or a command name, and when it's a key sequence like `o` and `g0`, `createTab` will invoke the mapping rule when a new tab gets ready.

If you're using global (browser-level) shortcuts, then `shortcut createTab $then="Vomnibar.activate"` should also work.

Detailed syntax and usage: https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands

**Comment by conrad000000** [comment]
For anyone who is still looking to implement this, a good solution that doesn't require creating a new tab is to modify your search engine url to use http inline javascript like this: `javascript:window.open('google.com/search?q=%s','_blank')`
This opens a new tab and is suprisingly clean and doesnt effect the current page's url at all.
