### ISSUE TITLE
hope make it works in microsoft edge

### ISSUE THREAD

**Issue by zzx41375004** [gdh1995/vimium-c-helpers#19]
Pdf viewer for vimium C does not work in Microsoft edge.
it can be successfully installed using crx package, but the shortcut key work wrongly, and in several minutes the extention will crash.
For some reasons Microsoft Edge is much more convenient than chrome,  so i hope pdf-viewer can work in it, thanks.

**Comment by gdh1995** [comment]
Hello I've updated the extension and its PDF viewer is latest now, so you may retry it.

If your MS Edge is Chromium-based then it should work well. If you are using an old MS Edge (EdgeHTML-based), whose version number is smaller than 20, then the browser may lack some features to make this extension work.

By default, on MS Edge this extension will try to work with `Vimium C for MS Edge` (https://microsoftedge.microsoft.com/addons/detail/aibcglbfblnogfjhbcmmpobjhnomhcdo), but not `Vimium C for Chrome` (https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg).
So if you installed Vimium C for Chrome on MS Edge, this extension would fail in auto finding Vimium C.

The latest `2.14.191` version should have fixed it by auto-retrying connecting to Vimium C for Chrome. If you find it fails again, please try these steps:
1. open `edge://extensions/?options=nacjakoppgmdcpemlfnfegmlhipddanj`
2. right-click content of the options page, like the text of `View position on load`, and select `Inspect`
3. Edge should popup a `DevTools` window, and please go to its `Console` panel
4. type `localStorage.removeItem('targetExtensionInjector')` and press `Enter`
5. open a PDF file to watch whether Vimium C works or not

![image](https://user-images.githubusercontent.com/5547703/163979131-68b9f3ea-94b8-4282-99ca-3af89898c58f.png)
