### ISSUE TITLE
English grammer error in Firefox detail, maybe

### ISSUE THREAD

**Issue by in-character** [gdh1995/vimium-c-helpers#2]
![Screenshot from 2020-04-21 18-56-47](https://user-images.githubusercontent.com/52375886/79858440-ffd1e180-8401-11ea-839d-54455203cc5a.png)

Detail: 
This web extension takes over your browser's new tab settings,
and it can move **focus of** a new tab from address bar to page content.

`focus of` ?

**Comment by gdh1995** [comment]
`focus`: a noun, the target that the browser is focusing

**Comment by in-character** [comment]
我咋还感觉那么别扭呢 this sentence

**Comment by gdh1995** [comment]
May replace it with "move the focus of"?

**Comment by in-character** [comment]
你和我想一块去了

**Comment by in-character** [comment]
这个新标签页还有其他开发计划吗

**Comment by gdh1995** [comment]
没了

**Comment by gdh1995** [comment]
基本上就是维护，附带的 vomnibar.html 需要更新的话就发一版新的
