### ISSUE TITLE
Firefox: newtab: vomnibar.html redirects to about:blank

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c-helpers#20]
I've set new tab URL to be `vomnibar.html`, and new tab displays that page for a second then redirects to about:blank

**Comment by mizzunet** [comment]
I see that Vomnibar doesn't open on newtaboverride. Though I have newtaboverride@agenedia.com in settings

**Comment by gdh1995** [comment]
`vomnibar.html` is designed not to show as a tab - it should always be a dialog (iframe). So you may let `newtab.html` auto run `Vomnibar.activate` to achieve a similar effect.

As said in https://github.com/gdh1995/vimium-c-helpers/issues/16#issuecomment-917598571 :

> Vimium C v1.92 has supported this feature: `map t createTab $then="Vomnibar.activate"`.
> 
> `$then` can be a mapped key sequence or a command name, and when it's a key sequence like `o` and `g0`, `createTab` will invoke the mapping rule when a new tab gets ready.
> 
> If you're using global (browser-level) shortcuts, then `shortcut createTab $then="Vomnibar.activate"` should also work.
> 
> Detailed syntax and usage: https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands

**Comment by mizzunet** [comment]
> Vimium C v1.92 has supported this feature: map t createTab $then="Vomnibar.activate".

That's cool. But the cursor is focused at address bar not on Vomnibar.

**Comment by gdh1995** [comment]
Then you may use this `NewTab Adapter` and enable its `Focus web page when creating a new tab` option.

I recommend another way: never use `Ctrl+T` or click the `Plus` button on the tab bar, but just use shortcuts of Vimium C to create tabs. I've added `Alt+T` as `createTab` on `chrome://extensions/shortcuts` (doc: https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#shortcuts), and then I don't need `NewTab Adapter` on my Edge browser.

**Comment by mizzunet** [comment]
That's better
