### ISSUE TITLE
功能请求：在打开新标签后自动执行o命令

### ISSUE THREAD

**Issue by mefengl** [gdh1995/vimium-c-helpers#28]
作为配置功能，默认不开启。
想要这个功能是因为打开新标签页，大部分的操作都是按下o然后搜索

**Comment by gdh1995** [comment]
```
map t createTab $then="Vomnibar.activate"
```

**Comment by mefengl** [comment]
`shortcut createTab $then="Vomnibar.activate"` 这个命令能响应Command+T吗？尝试了下不行

**Comment by gdh1995** [comment]
不能，有的快捷键是浏览器不允许覆盖

**Comment by mefengl** [comment]
@gdh1995 这个功能可不可以通过新标签页本身来完成，比如 新标签页等500ms给插件发个事件，相当与trigger

**Comment by gdh1995** [comment]
为什么要本身做？现在会出问题吗，需要等的话可以在vimium c里写
```
shortcut createTab $then="<v-omni>"
run <v-omni> 500wait+Vomnibar.activate
```

**Comment by gdh1995** [comment]
你怎么写的，看看你写的自定义快捷键规则？vimium c 版本是多少？

**Comment by mefengl** [comment]
`run t createTab+Vomnibar.activate`
Vimium C [1.99.90], Google Chrome 108, macOS.

**Comment by gdh1995** [comment]
我在Chrome 107的全新配置文件上，vimium c 和 newtab adapter能正常配合，t 会创建新标签并显示 Vomnibar，你按 t 后的效果都是什么，说详细点？

**Comment by mefengl** [comment]
我t也能正常运行的，指的是之前说的Alt+t的快捷键没有用

**Comment by mefengl** [comment]
我t也能正常运行的，指的是之前说的Alt+t的快捷键没有用

**Comment by mefengl** [comment]
我t也能正常运行的，指的是之前说的Alt+t的快捷键没有用

**Comment by mefengl** [comment]
我t也能正常运行的，指的是之前说的Alt+t的快捷键没有用

**Comment by gdh1995** [comment]
你Alt+T怎么配置的？

**Comment by mefengl** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/71683364/209188025-b155d819-d637-4af5-afcc-172e1c4b485c.png">

**Comment by gdh1995** [comment]
这儿只表示快捷键绑到了 `createTab` 这个命令，和 `run t createTab+Vomnibar.activate` 没关系

**Comment by gdh1995** [comment]
要修改这里的全局快捷键的行为，需要换写法
```
shortcut createTab $then="Vomnibar.activate"
```

**Comment by mefengl** [comment]
问题解决了
