### ISSUE TITLE
Allow dark theme

### ISSUE THREAD

**Issue by amynbe** [gdh1995/vimium-c-helpers#3]
The blank page doesn't play well with my dark chrome theme. Can you allow css styling or maybe just a default alternative dark if that's easier?

Also different request, would it be possible for the new tab page to trigger the vomnibar automatically?

**Comment by gdh1995** [comment]
Hello. NewTab Adapter has released a new version, and it will auto apply dark mode.

As for auto-starting Vomnibar, I haven't made a decision whether to add this feature or not.

**Comment by amynbe** [comment]
That's great, thank you!
